### ISSUE TITLE
[-t TIMEOUT]

### ISSUE THREAD

**Issue by cgarner-usgs** [netsecninja/teams-activity#3]
This is a helpful tool. I don't see [-t TIMEOUT] in the readme. I do see it in the [-h] console message. It isn't completely clear how this argument is used in the script. I can enter any value and get results, but when I enter my local power & sleep (20 mins) I don't see my known local timeouts in the results. If I set it to 15, I start to see some of them. Is it possible to get the timeout value from the logs? Also, if timeout entered doesn't match with system value throw exception? Also, I'd suggest add the [-t TIMEOUT] to the markdown.

**Comment by netsecninja** [comment]
Updated the readme to show the latest help output.

**Comment by cgarner-usgs** [comment]
On my system, [-t] TIMEOUT (per this implementation and version) appears to be the difference between:
- time between system idle and teams away status (7 mins for me), and
- time between system idle and auto lock (15 mins for me)
i.e., [-t] = 8.

**Comment by netsecninja** [comment]
You'll want to use the auto lock time

**Comment by cgarner-usgs** [comment]
I tried that and just tested while watching for expected times in the results. Using auto lock value (for me) produces a 7 min active status accounting error per timeout.

**Comment by netsecninja** [comment]
Yeah, overall the results of the script are not super accurate. I was tasked with using the Teams log to track user activity, and this was the best we could come up with at the time.

**Comment by cgarner-usgs** [comment]
Your script is excellent work. Do you know if Active, Away, Offline, etc.. are in the logs? Also, where are the logs if switched to new Teams?

**Comment by netsecninja** [comment]
I haven't tried with the new Teams.

**Comment by NIKL45** [comment]
Just as a hint on the location of the log files of the new Teams: 
I found some usable logged data about the users presence in the following locations:

`C:\Users\%USERNAME%\AppData\Local\Packages\MSTeams_8wekyb3d8bbwe\LocalCache\Microsoft\MSTeams\Logs\`  `-> MSTeams_2024-04-29_09-40-26.01.log`

`C:\Users\%USERNAME%\AppData\Local\Packages\MSTeams_8wekyb3d8bbwe\LocalCache\Microsoft\MSTeams\EBWebView\WV2Profile_tfw\Service Worker\CacheStorage\2b5c392d2730c0910fd56433cc5e73e510d0f2b4\9732e94e-f412-4336-9ee0-103f5c6797a7\`  `-> 7f0516b4179667f2_0`

I suppose the hashes might vary on other systems, but you can at least try to follow the path in the right direction. ;-)
